package de.dfki.gs.domain.utils

/**
 * Created by glenn on 11.07.14.
 */
public enum EconomicSector {

    ADMINISTRATIVE_AND_SUPPORT_SERVICE_ACTIVITIES,
    CONSTRUCTION,
    ELECTRICITY_GAS_STEAM_AND_AIR_CONDITIONING_SUPPLY,
    FINANCIAL_AND_INSURANCE_ACTIVITIES,
    HUMAN_HEALTH_AND_SOCIAL_WORK_ACTIVITIES,
    INFORMATION_COMMUNICATION,
    MANUFACTURING,
    OTHER_SERVICE_ACTIVITIES,
    PROFESSIONAL_SCIENTIFIC_AND_TECHNICAL_ACTIVITIES,
    PUBLIC_ADMINISTRATION_DEFENCE_COMPULSORY_SOCIAL_SECURITY,
    TRANSPORTATION_AND_STORAGE,
    WATER_SUPPLY_SEWERAGE_WASTE_MANAGEMENT_AND_REMEDIATION_ACTIVITIES,
    WHOLESALE_AND_RETAIL_TRADE_REPAIR_OF_MOTOR_VEHICLES_AND_MOTORCYCLES

}